### ISSUE TITLE
When depositing items at the bank, they disappear momentarily.

### ISSUE THREAD

**Issue by geheur** [elgbar/instant-inventory#7] opened 2023-04-18 17:41 UTC
https://cdn.discordapp.com/attachments/442492468307427330/1096596190071640144/RuneLite_-_Boynk_2023-04-14_19-00-52.mp4

**Comment by b-licorice** [comment] 2023-04-19 22:48
Came here to say this as well, plugin currently seems to be broken.

**Comment by elgbar** [comment] 2023-04-21 12:05
Oops, yeah that's a problem. 
I think the problem is that I'll always hide items when your deposit any amount.

The workaround is to disable/untick the `Deposit Items Instantly` feature for now

**Comment by elgbar** [comment] 2023-04-21 16:52
Fixed in [v1.1.1](https://github.com/elgbar/instant-inventory/releases/tag/v1.1.1)

**Closed by elgbar** 2023-04-21 16:52 UTC
Labels: bug
