### ISSUE TITLE
Bring back old version

### ISSUE THREAD

**Issue by roso1** [elgbar/instant-inventory#14] opened 2024-02-24 02:39 UTC
Can you bring back the old version of instant inventory this no one feels so buggy and weird.

**Comment by BrickPotato** [comment] 2024-02-24 18:46
I agree - I much preferred the old version. This one is broken.

**Comment by elgbar** [comment] 2024-02-25 13:24
Could you describe whats broken with the new version? 

Try changing the advanced settings It might be the new `Min Changed Millis`, try setting that to `0`. I appreciate feedback on what the default advanced values feels the best.


You can also disable a specific feature you don't like in the plugin config

**Comment by roso1** [comment] 2024-02-26 03:02
- Shift click wield to instantly dropping a item feels terrible. This is used for staff in p1 of verzik.
- When you switch gear sometimes it instantly switches and then sometimes it just disappears for a tick then switches. Its extremely inconsistent .

I've trained changing all the settings to make it like the old version but it just feels broken.

**Comment by elgbar** [comment] 2024-02-26 11:05
Thanks for the feedback. This update shouldn't have changed any existing behaviour, except for the `Min Changed Millis` mentioned above.

>Shift click wield to instantly dropping a item feels terrible

This seems to be the same bug as issue #13 

>When you switch gear sometimes it instantly switches and then sometimes it just disappears for a tick then switches. Its extremely inconsistent

This seems like a new bug. Do you get the different behaviour for the same items? Or do different items behave differently? I'm trying to pinpoint what goes wrong

**Comment by TV-cmd** [comment] 2024-03-02 12:28
**1)** When I try to [SHIFT] + [LMB] to to 'Wield' bolts, I can't even do that (have to disable plugin, as I'm prevented from wielding them).

**2)** Group ironman bank storage; Upon depositing items to the group storage, with this plugin enabled, the items actually go to the storage, however the items "appear" on my inventort still. having the option to still "deposit" them, even though they don't actually exist in my inventory anymore.

**Comment by elgbar** [comment] 2024-03-02 18:39
1) Will be fixed in the next version, and is also a duplicate of #13 
2) This is a different issue, could you create a new issue for this?

**Closed** 2024-04-11 14:58 UTC
Labels: question, wontfix
